version: '3'
services:
  test:
    # build: ./
    image: pwn_ret2text_2
    environment:
      # 仅为测试用flag
      FLAG: "#FLAG#"
    ports:
      # 设置了暴露端口
      - "#PORT#:9999"
    restart: unless-stopped
